export const requisition = {
  id: 22,
  company: "Drug International Ltd. (Unit 03)",
  address: "House No. 03, Flat No. A7, Road - Garib-E-Newaz Aveneue",
  phone: "88-02-48956715, 88-02-48956716",
  email: "mornin2morningrouppbd.com",
  date: "20 NOV, 2024",
  expectedDate: "23 NOV, 2024",
  priority: "Urgent",
  status: "Pending",
  items: [
    {
      id: "01",
      name: "Printer Toner",
      itemId: "10863786",
      quantity: "15 pc.",
      description: "Model: HP Laser Jet 2035",
      remarks: "5 gb",
    },
    {
      id: "02",
      name: "Printer Toner",
      itemId: "10863786",
      quantity: "15 pc.",
      description: "Model: HP Laser Jet 2035",
      remarks: "5 gb",
    },
    {
      id: "03",
      name: "Printer Toner",
      itemId: "10863786",
      quantity: "15 pc.",
      description: "Model: HP Laser Jet 2035",
      remarks: "5 gb",
    },
    {
      id: "04",
      name: "Printer Toner",
      itemId: "10863786",
      quantity: "15 pc.",
      description: "Model: HP Laser Jet 2035",
      remarks: "5 gb",
    },
  ],
  files: [
    { name: "Files.pdf", size: "45 KB" },
    { name: "Files.pdf", size: "45 KB" },
  ],
};
